require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  Exclude:
    - 'spec/examples/**/*'
    - 'config/**/*'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'
    - 'db/**/*'
    - 'bin/**/*'

Style/HashLikeCase:
  Enabled: false

RSpec/BlockLength:
  Exclude:
    - 'spec/**/*'

RSpec/MultipleExpectations:
  Max: 3

RSpec/MultipleMemoizedHelpers:
  Max: 9

RSpec/MessageSpies:
  Enabled: false
